import numpy as np

#Colors
REANLEA_PURPLE_DARK_FILL = "#331B5D"
REANLEA_PURPLE_DARKER = "#3B0893"
REANLEA_PURPLE = "#8c4dfb"
REANLEA_VIOLET = "#d7b5fe"

REANLEA_BLUE = "#650FFA"
REANLEA_BLUE_DARKER = "#02034E"

REANLEA_YELLOW = "#ffff5c"
REANLEA_YELLOW_DARKER = "#7F7F2D"

REANLEA_GREEN_LIGHTER = "#00cc70"
REANLEA_GREEN = "#008f4f"
REANLEA_GREEN_DARKER = "#004F2C"

REANLEA_WARM_BLUE = "#08B6CE"
REANLEA_WARM_BLUE_DARKER = "#044263"

REANLEA_ORANGE = "#FFB413"
REANLEA_ORANGE_DARKER = "#714400"

REANLEA_CHARM = "#FF5752"
REANLEA_CHARM_DARKER = "#6F001F"

REANLEA_FONT = "CMU Serif"
REANLEA_MONO = "SF Mono"

REANLEA_BACKGROUND_COLOR="#170526"


# Sizes relevant to default camera frame
ASPECT_RATIO = 16.0 / 9.0
FRAME_HEIGHT = 8.0
FRAME_WIDTH = FRAME_HEIGHT * ASPECT_RATIO
FRAME_Y_RADIUS = FRAME_HEIGHT / 2
FRAME_X_RADIUS = FRAME_WIDTH / 2

DEFAULT_PIXEL_HEIGHT = 1080
DEFAULT_PIXEL_WIDTH = 1920
DEFAULT_FPS = 30

SMALL_BUFF = 0.1
MED_SMALL_BUFF = 0.25
MED_LARGE_BUFF = 0.5
LARGE_BUFF = 1

DEFAULT_MOBJECT_TO_EDGE_BUFFER = MED_LARGE_BUFF
DEFAULT_MOBJECT_TO_MOBJECT_BUFFER = MED_SMALL_BUFF