REANLEA_PURPLE_DARK_FILL = "#331B5D"
REANLEA_PURPLE_DARKER = "#3B0893"
REANLEA_PURPLE = "#8c4dfb"
REANLEA_VIOLET = "#d7b5fe"

#REANLEA_BLUE = "#650FFA"
REANLEA_BLUE_DARKER = "#02034E"

REANLEA_YELLOW = "#ffff5c"
REANLEA_YELLOW_DARKER = "#7F7F2D"

REANLEA_GREEN_LIGHTER = "#00cc70"
REANLEA_GREEN = "#008f4f"
REANLEA_GREEN_DARKER = "#004F2C"

REANLEA_WARM_BLUE = "#08B6CE"
REANLEA_WARM_BLUE_DARKER = "#044263"

REANLEA_ORANGE = "#FFB413"
REANLEA_ORANGE_DARKER = "#714400"

REANLEA_CHARM = "#FF5752"
REANLEA_CHARM_DARKER = "#6F001F"

REANLEA_FONT = "CMU Serif"
REANLEA_MONO = "SF Mono" 

REANLEA_BACKGROUND_COLOR="#00001a"

#PURPLE COLOR SHADES
REANLEA_PURPLE = "#800080"
REANLEA_PURPLE_MAGENTA = "#FF00FF"
REANLEA_PURPLE_PINK_FLAMINGO = "#FF66FF"
REANLEA_PURPLE_VIOLET = "#FF99FF"
REANLEA_PURPLE_SNUFF = "#FFCCFF"
REANLEA_PURPLE_MDIUM = "#B380FF"


#VIOLET COLOR SHADES
REANLEA_VIOLET_DEEP = "#9900CC"
REANLEA_VIOLET_HELIOTROPE_DARKER = "#CC00FF"
REANLEA_VIOLET_HELIOTROPE = "CC66FF"
REANLEA_VIOLET_MAUVE = "#CC99FF"       


#BLUE VIOLET COLOR SHADES
REANLEA_BLUE_VIOLET = "#9933FF"
REANLEA_BLUE_VIOLET_LIGHTER = "9966FF"
REANLEA_BLUE_VIOLET_PORTAGE = "9999FF"


#BLUE COLOR SHADES
REANLEA_BLUE_LAVENDER = "#CCCCFF"
REANLEA_BLUE_AQUA = "#00FFFF"
REANLEA_BLUE = "0066FF"

#GREEN COLOR SHADES
REANLEA_GREEN = "#00FF00"
REANLEA_GREEN_LIGHT = "#66FF99"
REANLEA_GREEN_YELLOW = "#99FF33"
REANLEA_GREEN_JADE = "#00CC70"


#YELLOW COLOR SHADE
REANLEA_YELLOW = "#FFFF00"



REANLEA_PURPLE_MEDIUM_SLATE_BLUE = "#8c4dfb"
REANLEA_PURPLE_LIGHT_SLATE_BLUE="#8c66ff"


#MAGENTA COLOR CODES
REANLEA_MAGENTA = "#FF00FF"
REANLEA_MAGENTA_PINK_FLAMINGO = "#FF66FF"


REANLEA_AQUA = "#00ffff"
REANLEA_RED = "FF0000"

REANLEA_LIGHT_SLATE_BLUE = "#9966ff"
REANLEA_MINDARO = "#CCFF66"

REANLEA_BLUE_VIOLET = "#9933ff"
REANLEA_GREEN_YELLOW="#99ff33"

REANLEA_PORTAGE = "#9999ff" 
REANLEA_CANARY = "FFFF99"

REANLEA_LIGHT_SKY_BLUE = "#99ccff"  
REANLEA_PEACH_ORANGE = "#ffcc99"    

REANLEA_FEIJOA = "#99ff66"
REANLEA_HELIOTROPE = "#CC66FF"

REANLEA_LIME= "#00ff00"


#PURPLE VARIATION
REANLEA_PURPLE_DARK_FILL = "#331B5D"
REANLEA_PURPLE_DARKER = "#3B0893"


#WHITE VARIATION
REANLEA_WHITE_WHISPER = "#E6E6E6"


#VIOLET VARIATION
REANLEA_VIOLET = "#d7b5fe"
REANLEA_VIOLET_LAVENDER_BLUE = "#ccccff"
REANLEA_VIOLET_MAUVE = "#cc99ff"

REANLEA_SAFRON="#ff9933"


#BLUE VARIATION
REANLEA_BLUE = "#650FFA"
REDUCIBLE_BLUE_DARKER = "#02034E"
REANLEA_WARM_BLUE = "#08B6CE"
REANLEA_WARM_BLUE_DARKER = "#044263"


#YELLOW VARIATION
REANLEA_YELLOW = "#FFFF00"
REANLEA_YELLOW_LASER_LEMON = "#ffff5c"
REANLEA_YELLOW_CANNERY = "#FFFF99"
REANLEA_YELLOW_CREAM = "#ffffcc"
REANLEA_YELLOW_DARKER = "#7F7F2D"


#GREEN VARIATION
REANLEA_GREEN_LIGHTER_1="00ff8c"
REANLEA_GREEN_LIGHTER = "#00cc70"
REANLEA_GREEN = "#008f4f"
REANLEA_GREEN_DARKER = "#004F2C"
REANLEA_GREEN_SCREAMIN = "#66ff66"
REANLEA_GREEN_FREESPEECH="#1AFF1A"
REANLEA_GREEN_AQUAMARINE="#66ffd9"


#RED VARIATION
REANLEA_ORANGE = "#FFB413"
REANLEA_ORANGE_DARKER = "#714400"
REANLEA_CHARM = "#FF5752"
REANLEA_CHARM_DARKER = "#6F001F"


#PINK VARIATION
REANLEA_PINK_HELIOTROPE ="#D966FF" 



REANLEA_BACKGROUND_COLOR="#00001a"